# Generated by Django 5.1.5 on 2025-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vreme_dodavanja', models.DateTimeField(auto_now_add=True)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('broj_telefona', models.CharField(max_length=15)),
                ('adresa', models.CharField(max_length=100)),
                ('grad', models.CharField(max_length=50)),
                ('postanski_broj', models.CharField(max_length=20)),
            ],
        ),
    ]
